# Generated by Django 3.1.2 on 2020-11-03 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=50)),
                ('stu_num', models.IntegerField()),
                ('stu_class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolclass.tclass')),
            ],
            options={
                'db_table': 'student',
                'ordering': ['id'],
            },
        ),
    ]
