# Generated by Django 3.1.2 on 2020-11-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_num', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tempteacher',
                'ordering': ['id'],
            },
        ),
    ]
