# Generated by Django 3.1.2 on 2020-11-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('teacher_num', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=8)),
                ('teach_class', models.ManyToManyField(to='schoolclass.TClass')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
