# Generated by Django 3.1.2 on 2020-11-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_period', models.IntegerField()),
                ('subject_character', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'subject',
                'ordering': ['id'],
            },
        ),
    ]
