# Generated by Django 3.1.2 on 2020-11-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolclass', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_class',
            field=models.ManyToManyField(to='schoolclass.TClass'),
        ),
    ]
