# Generated by Django 3.1.2 on 2020-11-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subject_subject_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
